### Python Revision

###### Ex. WAP to replace all the vowels in a word with `*`

In [1]:
word = input("Enter a word - ")
for ch in "aeiou" :    
    word = word.replace(ch, "*")
word

Enter a word -  singapore


's*ng*p*r*'

In [2]:
word = input("Enter a word - ")
trans_obj = str.maketrans("aeiou", "*****")
word.translate(trans_obj)

Enter a word -  singapore


's*ng*p*r*'

In [3]:
word = input("Enter a word - ")
trans_obj = str.maketrans("aeiou", "*****", "@$")  # str.maketrans("old chars", "new chars", "chars to be removed")
word.translate(trans_obj)

Enter a word -  abcd$


'*bcd'

###### Ex. WAP to get sum of sales from the sales tuple

In [7]:
sales = ("$290", "$800", "$900", "$500")
# Comprehension - create a mutable container by applying an expression to a sequnce
sum([int(i.replace("$", "")) for i in sales])

2490

###### Ex. WAP to generate a list of squares of numbers from 1-10

In [8]:
[i**2 for i in range(1, 11)]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

###### Using map() function and func object

In [11]:
sales = ("$290", "$800", "$900", "$500")
func = lambda val : int(val.replace("$", ""))
sum(map(func, sales))

2490

###### Ex. WAP to sort the given list in DESC order

In [13]:
lst = ["bike", "flight", "car", "train"]
sorted(lst, reverse=True)

['train', 'flight', 'car', 'bike']

###### Ex. WAP to sort the list in ASC order of number characters in each word

In [15]:
lst = ["bike", "flight", "car", "train"]
sorted(lst, key = len)

['car', 'bike', 'train', 'flight']

###### Ex. WAP to sort the list in ASC order of last character of each word

In [17]:
lst = ["bike", "flight", "car", "train"]
sorted(lst, key = lambda word : word[-1])

['bike', 'train', 'car', 'flight']

###### Ex. WAP to sort the given dict in DESC order of salaries

In [22]:
employee = {"Rosie" : 40000, "Jane" : 30000, "Jack" :50000, "George" : 45000}
sorted(employee.items(), reverse=True, key = lambda val : val[1])

[('Jack', 50000), ('George', 45000), ('Rosie', 40000), ('Jane', 30000)]

In [23]:
dict(sorted(employee.items(), reverse=True, key = lambda val : val[1]))

{'Jack': 50000, 'George': 45000, 'Rosie': 40000, 'Jane': 30000}

### Function Arguments

#### 1. Required Positional Argument

In [26]:
def func(name, age):
    print(f"Name - {name} | Age - {age}")

In [28]:
func("Jane", 30)
func(30, "Jane")  # Positional Argument
func("Jane")  # Required Argument

Name - Jane | Age - 30
Name - 30 | Age - Jane


TypeError: func() missing 1 required positional argument: 'age'

In [29]:
len()

TypeError: len() takes exactly one argument (0 given)

In [32]:
lst = [1, 2, 3, 4, 5, 6]
lst.insert(5, 1) # insert 5 at position 1
lst

[1, 2, 3, 4, 5, 1, 6]

In [34]:
lst = [1, 2, 3, 4, 5, 6]
lst.insert("abcd", 1) # insert "abcd" at position 1
lst

TypeError: 'str' object cannot be interpreted as an integer

In [33]:
help(lst.insert)

Help on built-in function insert:

insert(index, object, /) method of builtins.list instance
    Insert object before index.



In [37]:
strg = "mississippi"
strg.replace("i", "*")

'm*ss*ss*pp*'

#### 2. Default Argument

In [38]:
help(strg.replace)

Help on built-in function replace:

replace(old, new, count=-1, /) method of builtins.str instance
    Return a copy with all occurrences of substring old replaced by new.

      count
        Maximum number of occurrences to replace.
        -1 (the default value) means replace all occurrences.

    If the optional argument count is given, only the first count occurrences are
    replaced.



In [39]:
strg = "mississippi"
strg.replace("i", "*", 2)

'm*ss*ssippi'

In [41]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



#### 3. Variable Length Argument

In [45]:
def func(name, *args, age = 19):
    print(f"Name - {name} | args - {args} | Age - {age}")

In [46]:
func("Jane", 70, 80, 90, 50, 20)  # all the arguments after name are packed into a tuple 'args'

Name - Jane | args - (70, 80, 90, 50, 20) | Age - 19


In [52]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [53]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [54]:
print(name, age)

jane 30


#### 4. Key-word Argument

In [58]:
def func(name, *args, age = 19):
    print(f"Name - {name} | args - {args} | Age - {age}")
func("Jane", 70, 80, 90, 50, age = 20) 

Name - Jane | args - (70, 80, 90, 50) | Age - 20


#### 5. Variable Length Key-word Argument

In [59]:
def func(name, *args, age = 19, **kwargs):
    print(f"Name - {name} | args - {args} | Age - {age} | kwargs - {kwargs}")
func("Jane", 70, 80, 90, 50, age = 20, mob = 98765432, gender = "F")

Name - Jane | args - (70, 80, 90, 50) | Age - 20 | kwargs - {'mob': 98765432, 'gender': 'F'}


#### Significance of `/` and `*`

- **`/`** - all the arguments before `/` must be positional only
- **`*`** - all arguments after `*` must be key-word only  

In [63]:
def func(name, age):
    print(f"Name - {name} | Age - {age}")

func("Jane", 30)  # positional argument
func(age = 30, name = "Jane") # key-word argument

Name - Jane | Age - 30
Name - Jane | Age - 30


In [68]:
def func(name, /, age):   # name must be positional only and age can be any type
    print(f"Name - {name} | Age - {age}")

func("Jane", 30)  
func("Jane", age = 30) 
func(age = 30, name = "Jane") # Error - name must be positional-only

Name - Jane | Age - 30
Name - Jane | Age - 30


TypeError: func() got some positional-only arguments passed as keyword arguments: 'name'

In [73]:
def func(name, *, age):  # name can be any type but age must be key-word only
    print(f"Name - {name} | Age - {age}")

func("Jane", age = 30) 
func(age = 30, name = "Jane") 
func("Jane", 30)   # Error - age must be keyword-only

Name - Jane | Age - 30
Name - Jane | Age - 30


TypeError: func() takes 1 positional argument but 2 were given

###### Example 

In [74]:
help(sorted)  # - iterable - require positional | key & reverse - default

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.

    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [75]:
sorted(iterable = [2, 1, 3, 4, 5]) # iterable is positional only arg

TypeError: sorted expected 1 argument, got 0

In [76]:
sorted(["car", "bike", "train"], len, True)  # key & reverse must key-word only

TypeError: sorted expected 1 argument, got 3

In [77]:
sorted(["car", "bike", "train"], key = len, reverse = True)  

['train', 'bike', 'car']

#### Packing and unpacking of tuples

In [ ]:
tup = 10, 20, 30  # packing of tuples
tup

(10, 20, 30)

In [48]:
a, b, c = tup  # unpacking of tuples
print(a)

10


In [50]:
# Declaring multiple variables in a single line - application of packing and unpacking tuples
name, age = "jane", 30
name

'jane'

###### Example - application of packing and unpacking of tuples wrt function call

In [78]:
def func(*args):
    print(args)

In [80]:
func(10, 20, 30, 40, 50)  # packing of tuples

(10, 20, 30, 40, 50)


###### Ex - Write details in a list to a file

In [83]:
# available built-in function - 
def write_to_file(name, age, gender) :
    with open("details.txt", "a") as file :
        file.write(f"{name} | {age} | {gender}\n")
        print(f"Details of {name} added to the file")

In [85]:
data = [
    ["Rosie", 30, "F"],
    ["Jack", 35, "M"],
    ["George", 28, "M"]
]

In [88]:
for i in data :
    write_to_file(*i)  # unpack the elements of the list into variables

Details of Rosie added to the file
Details of Jack added to the file
Details of George added to the file


<hr><hr>

# Basics of NumPy
- NumPy - Introduction and Installation
- NumPy - Arrays Data Structure ( 1D, 2D, ND arrays)
- Creating Arrays
- NumPy - Data Types
- Array Attributes
- Creating Arrays – Alternative Ways
- Sub-setting, Slicing and Indexing Arrays
- Operations on Arrays
- Array Manipulation


### NumPy – Introduction and Installation

- NumPy stands for ‘Numeric Python’
- Used for mathematical and scientific computations
- NumPy array is the most widely used object of the NumPy library

#### Installing numpy

In [90]:
pip install numpy
pip install pandas
pip install matplotlib
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


#### Importing numpy

In [89]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Arrays Data Structure

An `Array` is combination of homogenous data objects and can be indexed across multiple dimensions

#### Arrays are –
- ordered sequence/collection of Homogenous data
- multidimensional
- mutable


#### Creating Arrays – From list/tuple

- `np.array()` is used to create a numpy array from a list


#### Example on 1-D Array

In [91]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

#### Example on 2-D Array

In [92]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Array Attributes

- Attributes are the features/characteristics of an object that describes the object

- Some of the attributes of the numpy array are:
    - **shape** - Array dimensions
    - **size** - Number of array elements
    - **dtype** - Data type of array elements
    - **ndim** - Number of array dimensions
    - **dtype.name** - Name of data type
    - **astype** - Convert an array to a different type


In [93]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
arr.shape  # - (row, cols)

(3, 4)

In [95]:
arr.size

12

In [96]:
arr.ndim

2

In [97]:
arr.dtype

dtype('int64')

In [98]:
arr.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### Indexing, Slicing and Boolen Indexing

In [99]:
arr = np.random.randint(5, 50, size = 10)
arr

array([12, 34, 32, 27, 13,  8, 19, 16, 19, 26], dtype=int32)

#### 1-D Arrays

###### Ex. Extract first 3 elements

In [100]:
arr[0:3]

array([12, 34, 32], dtype=int32)

###### Ex. Extract last 5 elements

In [101]:
arr[-5 : ]

array([ 8, 19, 16, 19, 26], dtype=int32)

###### Ex. Extract element at position 2

In [103]:
arr[2]  # indexing

np.int32(32)

###### Ex. Extract elements at index position 2, 5, 9.

In [102]:
arr[[2, 5, 9]]  # indexing on mutiple positions

array([32,  8, 26], dtype=int32)

In [104]:
arr[[9, 2, 5]]  # indexing on mutiple positions

array([26, 32,  8], dtype=int32)

###### Ex. Extract elements less than 20

In [105]:
# Filtering based on condition
arr < 20  # returns a bool array

array([ True, False, False, False,  True,  True,  True,  True,  True,
       False])

In [107]:
# Filtering based on condition
arr[arr < 20]  

array([12, 13,  8, 19, 16, 19], dtype=int32)

### 2-D Arrays

In [108]:
arr = np.random.randint(5, 50, size = (6,4))
arr

array([[ 9, 49, 39, 41],
       [32, 40, 42, 16],
       [22, 14, 13, 49],
       [ 9, 49, 44, 17],
       [12, 13, 43,  8],
       [48, 45, 47, 15]], dtype=int32)

###### Ex. Extract first 3 rows

In [109]:
arr[0:3]

array([[ 9, 49, 39, 41],
       [32, 40, 42, 16],
       [22, 14, 13, 49]], dtype=int32)

###### Ex. Extract last 2 rows

In [110]:
arr[-2 :]

array([[12, 13, 43,  8],
       [48, 45, 47, 15]], dtype=int32)

###### Ex. Extract column at index 1

In [111]:
arr[ : , 1]  # returns 1D array

array([49, 40, 14, 49, 13, 45], dtype=int32)

###### Ex. Extract row 2 and 3 and column 2 and 3 (index-wise)

In [112]:
arr[2:4, 2:4]

array([[13, 49],
       [44, 17]], dtype=int32)

###### Ex. Extract values less than 25

In [113]:
arr[arr < 25]

array([ 9, 16, 22, 14, 13,  9, 17, 12, 13,  8, 15], dtype=int32)

###### Ex. Identify largest value. Extract values less than half of largest values

In [118]:
arr[arr < np.max(arr)/2]

array([ 9, 16, 22, 14, 13,  9, 17, 12, 13,  8, 15], dtype=int32)

### Examples on Coffee Shop Data Set

#### Coffee Shop

Mr. Alex owns a huge chain of coffee shop franchises. His franchises are spread across various states in India. There are in all 13 products sold across 156 franchises. Each franchise manager records their monthly sales and profits and compares with its corresponding targeted values. Let us start learning various attributes of numpy and pandas using the Coffee Shop dataset.


Fields in dataset -

- Product Name
- Actual Sales
- Actual Profits
- Targeted Sales
- Targeted Profits

#### Ex.  Create an array of coffee products, sales and profits

In [120]:
coffee_products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array( [52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])

###### Ex. How many products are there in the dataset?

In [121]:
coffee_products.size

10

###### Ex.  Sales greater than 50,000

In [122]:
sales[sales > 50000]

array([52248., 71060., 60014., 69925.])

###### Ex.  Identify Losses

In [123]:
profits[profits < 0]

array([-2954.])

###### Ex.  Products in loss

In [124]:
coffee_products[profits < 0]

array(['Green Tea'], dtype='<U17')

###### Ex.  Product with maximum Sales

In [126]:
coffee_products[sales == max(sales)]

array(['Colombian'], dtype='<U17')

In [127]:
coffee_products[sales == max(sales)][0]

np.str_('Colombian')

### Array Operations

#### Arithmetic operations on Arrays -
 - Addition, Substraction, Multiplication, Division, etc.
 - Operations on array and a scalar value
 - Operations between two arrays
 - Matrix Operations - Multiplication(np.dot()), Transpose(np.transpose())


#### Array and Scalar

In [128]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([7, 7, 6, 2, 4], dtype=int32)

In [129]:
arr1 + 5 # Addition

array([12, 12, 11,  7,  9], dtype=int32)

In [130]:
arr1 - 5 # Substraction

array([ 2,  2,  1, -3, -1], dtype=int32)

In [131]:
arr1 * 5 # Multiplication

array([35, 35, 30, 10, 20], dtype=int32)

In [132]:
arr1 / 5 # Division

array([1.4, 1.4, 1.2, 0.4, 0.8])

In [133]:
arr1 // 5 # Floor Division

array([1, 1, 1, 0, 0], dtype=int32)

In [134]:
arr1 % 5 # Modulus

array([2, 2, 1, 2, 4], dtype=int32)

#### Two Arrays

In [135]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([8, 6, 2, 7, 3], dtype=int32)

In [136]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([6, 5, 1, 5, 6], dtype=int32)

In [137]:
arr1 + arr2 # Addition

array([14, 11,  3, 12,  9], dtype=int32)

In [138]:
arr1 - arr2 # Substraction

array([ 2,  1,  1,  2, -3], dtype=int32)

In [139]:
arr1 * arr2 # Multiplication

array([48, 30,  2, 35, 18], dtype=int32)

In [140]:
arr1 / arr2 # Division

array([1.33333333, 1.2       , 2.        , 1.4       , 0.5       ])

In [141]:
arr1 // arr2 # Floor Division

array([1, 1, 2, 1, 0], dtype=int32)

In [142]:
arr1 % arr2 # Modulus

array([2, 1, 0, 2, 3], dtype=int32)

#### Relational operations on Arrays -
 - ==, !=, <, >, <=, >=
 - Operations on array and a scalar value
 - Operations between two arrays

#### Array and Scalar

In [143]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([7, 3, 7, 7, 7], dtype=int32)

In [144]:
arr1 == 5

array([False, False, False, False, False])

In [145]:
arr1 != 5

array([ True,  True,  True,  True,  True])

In [146]:
arr1 < 5

array([False,  True, False, False, False])

In [147]:
arr1 > 5

array([ True, False,  True,  True,  True])

In [148]:
arr1 <= 5

array([False,  True, False, False, False])

In [149]:
arr1 >= 5

array([ True, False,  True,  True,  True])

#### Two Arrays

In [150]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([1, 4, 1, 8, 4], dtype=int32)

In [151]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([9, 1, 2, 6, 5], dtype=int32)

In [152]:
arr1 == arr2

array([False, False, False, False, False])

In [153]:
arr1 != arr2

array([ True,  True,  True,  True,  True])

In [154]:
arr1 < arr2

array([ True, False,  True, False,  True])

In [155]:
arr1 > arr2

array([False,  True, False,  True, False])

In [156]:
arr1 <= arr2

array([ True, False,  True, False,  True])

In [157]:
arr1 >= arr2

array([False,  True, False,  True, False])

#### Logical operations on Arrays -
 - np.logical_or()
 - np.logical_and()
 - np.logical_not()
 - np.logical_xor()

In [158]:
arr1 = np.random.randint(1,10,size = 5)
arr1

array([1, 8, 7, 5, 6], dtype=int32)

In [159]:
arr2 = np.random.randint(1,10,size = 5)
arr2

array([4, 3, 9, 8, 2], dtype=int32)

In [160]:
np.logical_and(arr1 > 5, arr2 > 5)

array([False, False,  True, False, False])

In [161]:
np.logical_or(arr1 > 5, arr2 > 5)

array([False,  True,  True,  True,  True])

In [162]:
np.logical_not(arr1 > 5)

array([ True, False, False,  True, False])

In [163]:
np.logical_xor(arr1 > 5, arr2 > 5)

array([False,  True, False,  True,  True])

#### Set Operations on Arrays

Applicable to 1-D Ararys only

- np.unique() - Find the unique elements of an array.
- np.in1d() - Test whether each element of a 1-D array is also present in a second array.
- np.intersect1d() - Find the intersection of two arrays.
- np.setdiff1d() - Find the set difference of two arrays.
- np.union1d() - Find the union of two arrays.

In [164]:
arr1 = np.random.randint(1, 10, size = 10)
arr1

array([6, 2, 7, 7, 6, 9, 3, 9, 6, 5], dtype=int32)

In [165]:
np.unique(arr1)

array([2, 3, 5, 6, 7, 9], dtype=int32)

In [166]:
np.unique(arr1, return_index= True, return_counts=True)

(array([2, 3, 5, 6, 7, 9], dtype=int32),
 array([1, 6, 9, 0, 2, 5]),
 array([1, 1, 1, 3, 2, 2]))

In [167]:
arr2 = np.random.randint(1, 5, size = 10)
arr2

array([4, 1, 3, 2, 1, 1, 4, 1, 4, 1], dtype=int32)

In [168]:
np.in1d(arr1, arr2)  # depricated in 3.12 onwards

C:\Users\vaide\AppData\Local\Temp\ipykernel_18584\3141298059.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(arr1, arr2)


array([False,  True, False, False, False, False,  True, False, False,
       False])

In [169]:
np.isin(arr1, arr2)  # alternate for in1d()

array([False,  True, False, False, False, False,  True, False, False,
       False])

In [170]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6, 7, 9], dtype=int32)

In [171]:
np.intersect1d(arr1, arr2)

array([2, 3], dtype=int32)

### Array Functions/Methods

- np.all(), np.any()
- arr.sum()
- arr.min(), arr.max(), arr.argmin(), arr.agrmax()
- np.round()
- np.mean(), np.median(), np.average(), np.percentile()


In [172]:
np.all(np.isin(arr1, arr2))  # all elements of arr1 are not in arr2

np.False_

###### Ex. Find the product with max sales

In [174]:
coffee_products[sales == max(sales)]

array(['Colombian'], dtype='<U17')

In [175]:
sales.argmax() # returns index position of max element

np.int64(2)

In [176]:
coffee_products[sales.argmax()]  # returns a str in this case

np.str_('Colombian')

### Examples on Coffee Shop Data Set


#### Data

In [177]:
import numpy as np
products = np.array(['Caffe Latte', 'Cappuccino', 'Colombian', 'Darjeeling', 'Decaf Irish Cream', 'Earl Grey', 'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'])
sales = np.array([52248.0, 14068.0, 71060.0, 60014.0, 69925.0, 27711.0, 19231.0, 24873.0, 32825.0, 44109.0])
profits = np.array([17444.0, 5041.0, 28390.0, 20459.0, 23432.0, 7691.0, -2954.0, 7159.0, 10722.0, 14902.0])
target_profits = np.array([15934.0, 4924.0, 31814.0, 19649.0, 24934.0, 8461.0, 7090.0, 7084.0, 10135.0, 16306.0])
target_sales = np.array([48909.0, 13070.0, 80916.0, 57368.0, 66906.0, 30402.0, 18212.0, 21628.0, 27336.0, 42102.0])

###### Ex. Identify the products meeting the Target Profits

In [180]:
profit_ach = products[profits >= target_profits]
profit_ach

array(['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Lemon', 'Mint'],
      dtype='<U17')

###### Ex. Are the above products meeting their sales target too?

In [181]:
sales_ach = products[sales >= target_sales]
sales_ach

array(['Caffe Latte', 'Cappuccino', 'Darjeeling', 'Decaf Irish Cream',
       'Green Tea', 'Lemon', 'Mint', 'Regular Espresso'], dtype='<U17')

In [190]:
if np.all(np.isin(profit_ach, sales_ach)) :
    print("Yes all profit target achievers are also sales achievers", profit_ach)
else:
    print(f"No! These products do not achieve sales target - {np.setdiff1d(profit_ach, sales_ach)}")

Yes all profit target achievers are also sales achievers ['Caffe Latte' 'Cappuccino' 'Darjeeling' 'Lemon' 'Mint']


In [189]:
if np.all(np.isin(sales_ach, profit_ach)) :
    print("Yes all sales target achievers are also profit achievers", profit_ach)
else:
    print(f"No! These products do not achieve profit target - {np.setdiff1d(sales_ach, profit_ach)}")

No! These products do not achieve profit target - ['Decaf Irish Cream' 'Green Tea' 'Regular Espresso']


### Array Manipulations

- **Changing Shape** – np.reshape()
- **Adding/Removing Elements** – np.append(), np.insert(), np.delete()
- **Splitting Arrays** – np.hsplit(), np.vsplit(), arr_obj.flatten()
- **Sorting Arrays** - arr_obj.sort(), arr_obj.argsort()

In [191]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### np.reshape()

In [192]:
arr = np.reshape(arr, (4, 3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.append()

In [193]:
np.append(arr, [10,20,30, 50, 40, 60]) # Flattens the array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 10, 20, 30, 50, 40,
       60])

In [195]:
np.append(arr, np.reshape(np.array([13, 14, 15]), (1, 3)), axis = 0) # axis = 0 denotes row-wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [197]:
np.append(arr, np.reshape(np.array([10, 20, 30, 40]), (4, 1)), axis = 1) # axis = 1 denotes col-wise

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30],
       [10, 11, 12, 40]])

#### np.insert()

In [198]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [199]:
np.insert(arr, 1, 5) # Flattens the arr and inserts 5 at index 1

array([ 1,  5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [200]:
np.insert(arr, 1, 5, axis=0) # Inserts [5, 5, 5] as row 1

array([[ 1,  2,  3],
       [ 5,  5,  5],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [201]:
np.insert(arr, 1, 5, axis=1) # Inserts [5, 5, 5, 5] as column 1

array([[ 1,  5,  2,  3],
       [ 4,  5,  5,  6],
       [ 7,  5,  8,  9],
       [10,  5, 11, 12]])

In [202]:
np.insert(arr, 1, [10, 20, 30, 40], axis=1)

array([[ 1, 10,  2,  3],
       [ 4, 20,  5,  6],
       [ 7, 30,  8,  9],
       [10, 40, 11, 12]])

In [203]:
np.insert(arr, 1, [10, 20, 30], axis=0)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### np.delete()

In [204]:
arr = np.reshape(np.arange(1,13), (4,3))
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [205]:
np.delete(arr, 1) # Flattens the arr and deletes element at index 1

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [206]:
np.delete(arr, 1, axis=0) # deletes row 1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [207]:
np.delete(arr, 1, axis=1) # deletes column 1

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

In [208]:
np.delete(arr,[0,2], axis=0) # deletes selected rows

array([[ 4,  5,  6],
       [10, 11, 12]])

In [209]:
np.delete(arr,[0,2], axis=1) # deletes selected columns

array([[ 2],
       [ 5],
       [ 8],
       [11]])

#### np.hsplit(), np.vsplit()

In [210]:
arr = np.reshape(np.arange(1, 25), (6,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [211]:
np.vsplit(arr, 2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [212]:
np.hsplit(arr, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

#### flatten()

In [213]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [215]:
arr.flatten() # returns a 1-D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [214]:
arr.flatten(order = "F") # returns a 1-D array

array([ 1,  5,  9, 13, 17, 21,  2,  6, 10, 14, 18, 22,  3,  7, 11, 15, 19,
       23,  4,  8, 12, 16, 20, 24])

In [ ]:
help(arr.flatten)

### Sorting Arrays

###### Ex. Identify products which are not achieving their profit target. Calculate their target status in percentage. Display the products in DESC order of their percentage status

In [243]:
profits < target_profits

array([False, False,  True, False,  True,  True,  True, False, False,
        True])

In [236]:
off_products = products[profits < target_profits]
off_targets = target_profits[profits < target_profits]
off_profits = profits[profits < target_profits]

In [237]:
percentage = np.round(off_profits/off_targets * 100, 2)
percentage[percentage < 0] = 0
percentage

array([89.24, 93.98, 90.9 ,  0.  , 91.39])

In [239]:
sort_order = percentage.argsort()[::-1]
sort_order  # Sorts the array and returns the index position os the sorted elements from the original array

array([1, 4, 2, 0, 3])

In [240]:
off_products = off_products[sort_order]
percentage = percentage[sort_order]

In [241]:
list(zip(off_products, percentage))

[(np.str_('Decaf Irish Cream'), np.float64(93.98)),
 (np.str_('Regular Espresso'), np.float64(91.39)),
 (np.str_('Earl Grey'), np.float64(90.9)),
 (np.str_('Colombian'), np.float64(89.24)),
 (np.str_('Green Tea'), np.float64(0.0))]

In [242]:
for i, j in zip(off_products, percentage) :
    print(f"{i} has achieved {j}% of its targets")

Decaf Irish Cream has achieved 93.98% of its targets
Regular Espresso has achieved 91.39% of its targets
Earl Grey has achieved 90.9% of its targets
Colombian has achieved 89.24% of its targets
Green Tea has achieved 0.0% of its targets


<hr><hr>